/**
 * Vocabulário visual único do GestÁgua.
 *
 * Os nomes exportados são semânticos para o produto, enquanto a implementação
 * fica centralizada na família Line do Remix Icon.
 */
export {
  RiAlertLine as AlertTriangle,
  RiArrowDownSLine as ChevronDown,
  RiArrowLeftDoubleLine as ChevronsLeft,
  RiArrowLeftLine as ArrowLeft,
  RiArrowLeftSLine as ChevronLeft,
  RiArrowRightDoubleLine as ChevronsRight,
  RiArrowRightSLine as ChevronRight,
  RiBarChartBoxLine as BarChart3,
  RiBox3Line as PackageOpen,
  RiBuilding2Line as Building2,
  RiCalendarLine as CalendarDays,
  RiCalendarScheduleLine as CalendarClock,
  RiCheckboxCircleLine as CheckCircle2,
  RiCircleLine as Circle,
  RiClipboardLine as ClipboardCheck,
  RiCloseLine as X,
  RiDashboardLine as LayoutDashboard,
  RiDownloadLine as Download,
  RiDropLine as Droplets,
  RiExternalLinkLine as ExternalLink,
  RiEyeLine as Eye,
  RiEyeOffLine as EyeOff,
  RiFileTextLine as FileText,
  RiFolderChartLine as FolderKanban,
  RiInformationLine as Info,
  RiInputField as TextCursorInput,
  RiKey2Line as KeyRound,
  RiLandscapeLine as LandPlot,
  RiLeafLine as Leaf,
  RiListCheck3 as ListChecks,
  RiLoader4Line as LoaderCircle,
  RiLogoutBoxRLine as LogOut,
  RiMapPinLine as MapPin,
  RiMegaphoneLine as Megaphone,
  RiMenuLine as Menu,
  RiMoneyDollarCircleLine as CircleDollarSign,
  RiPaletteLine as Palette,
  RiPlantLine as Trees,
  RiRefreshLine as RefreshCw,
  RiResetLeftLine as RotateCcw,
  RiRoadMapLine as Map,
  RiRouteLine as Route,
  RiRulerLine as Ruler,
  RiSearchLine as Search,
  RiSeedlingLine as Sprout,
  RiStackLine as Layers3,
  RiTableLine as Table2,
  RiTeamLine as Users,
  RiTimeLine as Clock3,
  RiToolsLine as Construction,
  RiTreeLine as TreePine,
  RiUploadLine as Upload,
  RiUserLine as UserRound,
  RiWallet3Line as WalletCards,
  RiWaterFlashLine as Waves,
} from '@remixicon/react';

export type { RemixiconComponentType } from '@remixicon/react';
